In [1]:
from embedding import pipeline as pipe
import pickle
from embedding.embedding_base import EmbeddingBase
import pandas as pd
from embedding import sentence_embedding
from classifier import recurrent_NN as rec
import numpy as np
from classifier import Adaboost_classi as classy

# Testing different preprocessing techniques performance

## Let's try first with Adaboost Classifier

In [4]:
ada1 = classy.Adaboost_classi(embedding_dimension=200)


##### We fit the model on each training matrix we created. For each different pre processing technique, we fit the model on the training matrix obtained using the summation of the embeddings (1) and on the one using their concatenation (0).

### Case 1 : Negation marking + lemmatization + replacement, vocab: 10 words min


In [13]:
arr0 = np.load("D://embedding_matrices//train_neg_mark_10_0.npz")
arr1 = np.load("D://embedding_matrices//train_neg_mark_10_1.npz")
arr1 = arr1['arr_0']
x = arr1[:,:-1]
y = arr1[:,-1]

##### Result summation

In [17]:
ada1.build()
ada1.train(x,y) 

Building model.
Training model
[0.74505  0.73265  0.7348   0.737075 0.7299  ]


##### Result concatenation

In [18]:
arr0 = arr0['arr_0']
x = arr0[:,:-1]
y = arr0[:,-1]
ada1.build()
ada1.train(x,y)

Building model.
Training model
[0.68045  0.665375 0.658175 0.651375 0.651825]


### Case 2 : full vocabulary, 10 words min

In [5]:
arr0 = np.load("D://embedding_matrices//train_10_full_12656_0.npz")
arr1 = np.load("D://embedding_matrices//train_10_full_12656_1.npz")
arr1 = arr1['arr_0']
arr0 = arr0['arr_0']

##### Results

In [6]:
arr0 = np.load("D://embedding_matrices//train_10_full_12656_0.npz")
arr1 = np.load("D://embedding_matrices//train_10_full_12656_1.npz")
arr1 = arr1['arr_0']
arr0 = arr0['arr_0']
x = arr0[:,:-1]
y = arr0[:,-1]
ada1.build()
ada1.train(x,y)
x = arr1[:,:-1]
y = arr1[:,-1]
ada1.build()
ada1.train(x,y)

Building model.
Training model
[0.676525 0.664375 0.649675 0.64375  0.64265 ]
Building model.
Training model
[0.744575 0.738725 0.7344   0.727225 0.728475]


### Case 3 : full vocabulary, 5 words min

In [8]:
arr0 = np.load("D://embedding_matrices//train_full_21175_0.npz")
arr1 = np.load("D://embedding_matrices//train_full_21175_1.npz")
arr1 = arr1['arr_0']
arr0 = arr0['arr_0']
x = arr0[:,:-1]
y = arr0[:,-1]
ada1.build()
ada1.train(x,y)
x = arr1[:,:-1]
y = arr1[:,-1]
ada1.build()
ada1.train(x,y)

Building model.
Training model
[0.67975  0.6726   0.665075 0.6458   0.651375]
Building model.
Training model
[0.742125 0.740225 0.7326   0.73465  0.72855 ]


### Case 4 : lemmatized, 5 words min

In [9]:
arr0 = np.load("D://embedding_matrices//train_lemm_18082_0.npz")
arr1 = np.load("D://embedding_matrices//train_lemm_18082_1.npz")
arr1 = arr1['arr_0']
arr0 = arr0['arr_0']
x = arr0[:,:-1]
y = arr0[:,-1]
ada1.build()
ada1.train(x,y)
x = arr1[:,:-1]
y = arr1[:,-1]
ada1.build()
ada1.train(x,y)

Building model.
Training model
[0.68185  0.6731   0.659225 0.65675  0.64905 ]
Building model.
Training model
[0.747275 0.7373   0.732575 0.7278   0.728425]


### Case 5 : lemmatized and replacement, 10 words min

In [10]:
arr0 = np.load("D://embedding_matrices//train_lemm_rep_10_10810_0.npz")
arr1 = np.load("D://embedding_matrices//train_lemm_rep_10_10810_1.npz")
arr1 = arr1['arr_0']
arr0 = arr0['arr_0']
x = arr0[:,:-1]
y = arr0[:,-1]
ada1.build()
ada1.train(x,y)
x = arr1[:,:-1]
y = arr1[:,-1]
ada1.build()
ada1.train(x,y)

Building model.
Training model
[0.67565  0.66215  0.6506   0.651775 0.648875]
Building model.
Training model
[0.653925 0.6729   0.67355  0.6757   0.664675]


### Case 6: lemmatized with stop words, 5 words min

In [11]:
arr0 = np.load("D://embedding_matrices//train_lemm_stop_17543_0.npz")
arr1 = np.load("D://embedding_matrices//train_lemm_stop_17543_1.npz")
arr1 = arr1['arr_0']
arr0 = arr0['arr_0']
x = arr0[:,:-1]
y = arr0[:,-1]
ada1.build()
ada1.train(x,y)
x = arr1[:,:-1]
y = arr1[:,-1]
ada1.build()
ada1.train(x,y)

Building model.
Training model
[0.6801  0.67535 0.66295 0.6671  0.6518 ]
Building model.
Training model
[0.7465   0.73465  0.734775 0.72555  0.734675]


### Case 6: negation_marking + lemmatized + replacement with stop words, 5 words min

In [12]:
arr0 = np.load("D://embedding_matrices//train_neg_mark_5_0.npz")
arr1 = np.load("D://embedding_matrices//train_neg_mark_5_1.npz")
arr1 = arr1['arr_0']
arr0 = arr0['arr_0']
x = arr0[:,:-1]
y = arr0[:,-1]
ada1.build()
ada1.train(x,y)
x = arr1[:,:-1]
y = arr1[:,-1]
ada1.build()
ada1.train(x,y)

Building model.
Training model
[0.689825 0.67745  0.667875 0.659575 0.660225]
Building model.
Training model
[0.739875 0.731225 0.7299   0.740125 0.730275]


In [13]:
arr0 = np.load("D://embedding_matrices//train_neg_mark_10_0.npz")
arr1 = np.load("D://embedding_matrices//train_neg_mark_10_1.npz")
arr1 = arr1['arr_0']
arr0 = arr0['arr_0']
x = arr0[:,:-1]
y = arr0[:,-1]
ada1.build()
ada1.train(x,y)
x = arr1[:,:-1]
y = arr1[:,-1]
ada1.build()
ada1.train(x,y)

Building model.
Training model
[0.689825 0.67745  0.667875 0.659575 0.660225]
Building model.
Training model
[0.74505  0.73265  0.7348   0.737075 0.7299  ]


In [14]:
arr0 = np.load("D://embedding_matrices//train_neg_mark_10_0.npz")
arr1 = np.load("D://embedding_matrices//train_neg_mark_10_1.npz")
arr1 = arr1['arr_0']
arr0 = arr0['arr_0']

### Training Matrix Negation Marking 10 

In [17]:
pd.DataFrame(arr1)

0         1         2         3         4         5         6    \
0       2.003153  0.059375  1.176305  3.099393 -1.480270  4.261483  0.943238   
1       1.321177  1.825059 -0.769256  0.178490 -0.718400  1.207151 -0.084270   
2       2.734488  3.936739  2.391126  0.460451 -0.578238  2.692345 -1.616632   
3       0.135106  3.985985  0.389060  1.600472 -2.463097  3.008654 -0.024798   
4       1.613785  5.386377  0.637572  2.182370 -0.739840  5.847832  0.362601   
...          ...       ...       ...       ...       ...       ...       ...   
199995  2.161770  2.376540  0.549252  0.757603 -0.539783  1.224371 -1.090748   
199996  6.215346  5.332097 -0.474458  3.778277 -1.145942  7.949866 -2.926236   
199997  3.411396  5.563155 -1.343509  2.165330 -0.979198  3.272943 -0.350629   
199998  2.895358  3.510256 -0.086647  1.355704 -1.642892  3.898547 -1.836652   
199999  4.218060  9.579492  1.227943  4.080159 -0.774645  5.737889 -1.520243   

             7         8         9    ...       191       192       193  \
0       4.699919 -3.448722 -0.142886  ...  1.045596 -0.496502 -2.010463   
1       1.154780 -1.641488  0.937143  ...  1.280981  0.965464 -0.973246   
2      -0.074683 -1.271235  2.182798  ... -1.101593 -0.507666 -2.275459   
3      -0.037095 -1.822041 -0.272107  ...  0.338051  0.004642 -2.601778   
4       2.185732 -1.529609  0.928507  ... -0.032873 -0.966383 -2.135091   
...          ...       ...       ...  ...       ...       ...       ...   
199995  1.117586 -0.951006 -0.808506  ...  0.917931  0.326258 -1.303018   
199996  2.767899 -4.679984 -0.992254  ...  3.229219  0.043773 -2.247994   
199997  1.206431 -4.226316  0.285101  ...  0.397136 -1.104894 -1.889345   
199998  1.553336 -2.044370 -1.004196  ...  1.201145 -1.087625 -1.780723   
199999  4.509464 -7.240996 -0.418048  ...  1.202845 -0.797265 -5.795557   

             194       195       196       197       198       199  200  
0      -0.434142 -1.273661 -0.963589  0.605833 -6.403092 -0.199765  0.0  
1      -1.519586  0.282107 -1.801000  1.383495 -1.647566  1.779701  0.0  
2      -0.834760 -1.990884 -1.445940 -1.416654 -2.017740  1.759486  0.0  
3      -1.545038 -2.024183 -1.997911  0.781345 -1.887818  2.361278  0.0  
4      -1.212612 -1.279975 -2.457171 -1.297063 -3.704950  1.203137  0.0  
...          ...       ...       ...       ...       ...       ...  ...  
199995 -1.055922 -1.285632  0.081401 -1.352616 -1.078003  1.330686  1.0  
199996 -3.709773 -3.846788 -5.735913 -0.529322 -3.589694  6.460107  1.0  
199997 -1.682679 -2.705730 -3.166605 -1.643026 -3.306980  3.329864  1.0  
199998 -2.044479 -2.705108 -3.959178  0.660978 -2.665578  5.364046  1.0  
199999 -3.640293 -4.994938 -1.735266  0.486415 -5.892075  6.767427  1.0  

[200000 rows x 201 columns]

### Training Matrix lemmatization and replacement 10

In [22]:
arr1 = np.load("D://embedding_matrices//train_lemm_rep_10_10810_1.npz")
arr1 = arr1['arr_0']
pd.DataFrame(arr1)

0         1         2         3         4         5         6    \
0      -0.364442  2.711838 -1.973383  1.721517 -2.512698  1.555344  4.958007   
1      -0.547912  0.561529 -1.754580 -1.130136 -0.304568  1.005415  1.183256   
2       1.118670  3.334513 -0.103789 -1.211855 -1.564432  3.705067  4.505796   
3       0.966103  3.638089 -1.711699 -0.869258 -3.289789  1.429641  2.584887   
4      -0.182926  2.608265 -0.514734  1.175587 -1.764631  0.792961  1.357220   
...          ...       ...       ...       ...       ...       ...       ...   
199995  0.062834  0.941035  0.639358 -0.700971  0.334113  0.610259  1.520712   
199996  0.488083  3.639241 -5.607270  3.555391 -2.886949  5.040390  8.506230   
199997  1.364439  6.920882 -0.689313 -0.566676 -3.809954  1.903388  4.127519   
199998  2.506945  4.622958 -1.796340 -0.925103 -0.625245 -0.357747  1.076692   
199999  0.594009  2.380545 -0.663650  0.199102 -0.279556  1.306124  6.850102   

             7         8         9    ...       191       192       193  \
0       2.567133 -0.175546  1.446702  ... -0.240848  0.313587  0.242469   
1      -0.033421  0.484009 -1.359124  ... -0.592055 -1.097049 -0.023258   
2      -0.094455 -1.155750  0.818007  ...  2.897853  1.533973  0.941882   
3       0.181641 -0.210630  1.007587  ... -0.681879 -1.759520 -0.232496   
4       0.123349  0.940386  0.531076  ...  1.554797 -1.125571  0.221238   
...          ...       ...       ...  ...       ...       ...       ...   
199995 -0.267464  0.343965 -1.044237  ... -1.614024 -0.304913 -0.652910   
199996 -0.619971 -1.174315  1.858987  ... -2.601829 -4.318220  1.902997   
199997  0.413602 -2.244772  1.099213  ...  0.965286 -2.060376  0.051719   
199998  1.051494 -1.053511 -0.798003  ...  0.582595 -0.880470 -0.685185   
199999 -2.002757 -1.981669  0.940994  ...  3.131499 -0.470769  0.746012   

             194       195       196       197       198       199  200  
0      -1.799657  1.713323  2.557487 -0.093983 -0.900870  1.692980  0.0  
1      -0.371026  1.504519  0.972150 -0.066232 -0.605402  0.266169  0.0  
2      -1.207514 -0.646047 -0.057464 -0.920259 -1.355515  0.844375  0.0  
3      -1.399346  0.713252 -1.153311  1.075085 -3.261237  0.879324  0.0  
4      -1.169966  0.047702 -0.031349  0.116110 -1.230358 -0.488179  0.0  
...          ...       ...       ...       ...       ...       ...  ...  
199995 -0.083011 -0.182136 -0.164620  0.341852 -1.212167  0.772141  1.0  
199996 -1.239073 -2.094194 -4.741051  0.160564 -3.697052  0.132502  1.0  
199997 -4.619251  0.388369 -3.389189  1.176797 -2.018846 -0.324313  1.0  
199998 -3.221213  1.341757 -2.525892  0.633955 -3.130941  1.439956  1.0  
199999 -1.574813 -0.227272 -0.050823 -2.548302 -2.000663  6.103354  1.0  

[200000 rows x 201 columns]

### Training matrix negative marking + replacement + lemmatization with 5 words

In [18]:
arr1 = np.load("D://embedding_matrices//train_neg_mark_5_1.npz")
arr1 = arr1['arr_0']
pd.DataFrame(arr1)

0         1         2         3         4         5         6    \
0       2.744243  0.064196  0.748382  2.884386 -1.478211  4.293972  0.781031   
1       1.337877  1.794864 -0.772354  0.171728 -0.746612  1.179160 -0.030814   
2       2.734920  3.841450  2.394832  0.462029 -0.668150  2.605818 -1.497973   
3       0.202673  3.920145  0.382464  1.597201 -2.540074  2.941425  0.115403   
4       1.659849  5.294436  0.622598  2.153962 -0.832203  5.753793  0.493405   
...          ...       ...       ...       ...       ...       ...       ...   
199995  2.179512  2.337249  0.554840  0.761305 -0.581756  1.190096 -1.020935   
199996  6.140747  5.154550 -0.259151  3.896883 -1.231015  7.721708 -2.961629   
199997  3.424637  5.452376 -1.307111  2.183368 -1.058126  3.195762 -0.281791   
199998  2.550781  3.569652 -0.397750  1.644187 -1.520765  4.607465 -1.295443   
199999  4.278479  9.408791  1.312502  4.128036 -0.946330  5.586507 -1.362473   

             7         8         9    ...       191       192       193  \
0       4.713445 -2.803378 -0.307988  ...  0.905514  0.001194 -2.188094   
1       1.151995 -1.632398  0.933478  ...  1.278587  0.937628 -0.974902   
2      -0.048700 -1.210978  2.137351  ... -1.088499 -0.554036 -2.293797   
3      -0.021783 -1.780407 -0.276521  ...  0.336696 -0.051184 -2.626957   
4       2.180077 -1.478825  0.909590  ... -0.023773 -1.022750 -2.165594   
...          ...       ...       ...  ...       ...       ...       ...   
199995  1.113243 -0.941638 -0.821973  ...  0.911122  0.286562 -1.323795   
199996  2.767134 -4.631724 -1.175217  ...  3.255477 -0.063861 -2.364963   
199997  1.200621 -4.178971  0.207321  ...  0.404540 -1.143802 -1.939367   
199998  1.038892 -1.950163 -1.353696  ...  1.103851 -0.995495 -2.154025   
199999  4.500982 -7.175237 -0.516261  ...  1.181782 -0.917781 -5.846586   

             194       195       196       197       198       199  200  
0      -0.396378 -2.081625 -0.680176  0.250862 -6.093755 -0.568403  0.0  
1      -1.526594  0.295314 -1.929564  1.297144 -1.645149  1.807026  0.0  
2      -0.860816 -1.951336 -1.737651 -1.539055 -2.008671  1.857043  0.0  
3      -1.544261 -2.003611 -2.314967  0.584318 -1.874683  2.465900  0.0  
4      -1.227489 -1.262520 -2.813847 -1.513003 -3.685473  1.314285  0.0  
...          ...       ...       ...       ...       ...       ...  ...  
199995 -1.049783 -1.268288 -0.120509 -1.448560 -1.077077  1.373479  1.0  
199996 -3.723600 -3.721205 -6.323569 -0.800615 -3.511398  6.413562  1.0  
199997 -1.689422 -2.694115 -3.479596 -1.821552 -3.310829  3.368952  1.0  
199998 -1.786899 -2.913442 -4.388548 -0.092228 -3.068846  4.851334  1.0  
199999 -3.631790 -4.913912 -2.449497  0.141840 -5.861332  6.910228  1.0  

[200000 rows x 201 columns]

### lemmatization + stop words 5 words

In [19]:
arr0 = np.load("D://embedding_matrices//train_lemm_stop_17543_0.npz")
arr1 = np.load("D://embedding_matrices//train_lemm_stop_17543_1.npz")
arr1 = arr1['arr_0']
arr0 = arr0['arr_0']

In [21]:
pd.DataFrame(arr1)

0         1         2         3         4         5         6    \
0       1.444335 -1.318472  0.346028  1.350200 -1.385962  2.767417  1.311231   
1       1.081177  1.244163 -0.844975 -0.605077 -0.474558  1.599846  0.544017   
2       0.251503  1.373665  0.767569 -1.226704 -0.501497  0.477874  1.980714   
3       0.710749  3.078687  0.205875  0.636671 -2.038502  2.830842  1.740228   
4       0.600336  3.964730  0.606346  0.795951 -0.117665  3.840555  1.484611   
...          ...       ...       ...       ...       ...       ...       ...   
199995  0.937364  1.175528 -0.092796  0.187754 -0.224659  0.531020 -0.210043   
199996  2.717598  2.772437 -0.876427  2.168068 -1.086708  5.918804 -1.076213   
199997  0.596723  3.747364 -1.204093 -0.363936 -0.686662  1.755927  0.968883   
199998  2.157615  1.785706  0.332653  0.942408 -1.691892  1.855060  0.552634   
199999  1.416145  3.955163  0.465564  1.325698 -0.289621  1.550797  1.960828   

             7         8         9    ...       191       192       193  \
0       3.328652 -1.137927 -0.049942  ...  0.969270  0.406134 -1.840788   
1       1.074949 -0.864517  0.913248  ...  1.517632  0.870794 -0.962172   
2      -0.500599  0.445129  1.927104  ... -2.019483  0.609414 -1.533673   
3       0.500313 -0.785484  0.367704  ...  1.376823 -0.925058 -3.293755   
4       1.645713  0.064729  1.208043  ...  0.763729 -1.436267 -0.953035   
...          ...       ...       ...  ...       ...       ...       ...   
199995  0.998402 -0.538856 -0.429381  ...  0.736004  0.072086 -1.130666   
199996  1.414478 -2.522229 -0.686380  ...  0.864480 -1.414399 -2.130669   
199997  1.221958 -1.282437  0.619975  ...  1.583072  0.699452 -1.804382   
199998  1.040187 -0.672752 -0.130366  ...  1.160739 -0.854388 -1.427779   
199999  2.620017 -2.083356  0.265323  ... -0.585904 -0.260417 -2.902417   

             194       195       196       197       198       199  200  
0       1.039715 -0.891630 -0.434733  0.137031 -4.814063 -1.888110  0.0  
1      -1.082150  0.442742 -1.644324  1.065287 -1.519401  1.735054  0.0  
2       1.044878 -0.113420 -0.553719 -0.645479 -0.508243  1.294903  0.0  
3      -0.815734 -1.249593 -3.441774 -0.429771 -1.264364  3.197393  0.0  
4       0.013847 -0.392686 -2.027880 -1.171190 -2.182281  0.264169  0.0  
...          ...       ...       ...       ...       ...       ...  ...  
199995 -0.570777 -0.419839 -0.127775 -1.196225 -0.380407  0.288348  1.0  
199996 -0.199844 -2.400389 -5.117435  0.754370 -4.115175  4.927545  1.0  
199997 -1.961779 -0.886282 -2.191551 -1.388790 -0.575552  1.803209  1.0  
199998 -0.985142 -1.888865 -3.311204 -0.499471 -1.765131  3.507219  1.0  
199999 -0.455114 -2.569437 -0.832484 -0.363861 -2.381242  2.399019  1.0  

[200000 rows x 201 columns]

### Building training matrix for full vocabulary 10 words


In [20]:
with open("vocabulary_10_full_12656.pkl", "rb") as f:
    voc = pickle.load(f)
with open("cooc_10_full_12656.pkl", "rb") as f:
    cooc = pickle.load(f)
    
emb = EmbeddingBase(embedding_name = "emb_10_full_12656.npz",
                 embedding_dimension = 200,
                 vocabulary = voc,
                 cooc = cooc,
                 load = True)

mat1 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg.txt","train_pos.txt"],
                          label_values=None,
                          input_entries=200000,
                          sentence_dimesion = 200,
                          output_location = "training_matrices\\train_10_full_12656_1")

mat2 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg.txt","train_pos.txt"],
                          label_values=None,
                          input_entries=200000,
                          aggregation_fun=sentence_embedding.no_embeddings,
                          sentence_dimesion = 100,
                          output_location = "training_matrices\\train_10_full_12656_0")

Working on  train_neg.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000
Working on  train_neg.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000


### Building training matrix for full vocabulary 5 words

In [23]:
with open("dictionary_full_21175.pkl", "rb") as f:
    voc = pickle.load(f)
with open("cooc_full_21175.pkl", "rb") as f:
    cooc = pickle.load(f)
    
emb = EmbeddingBase(embedding_name = "emb_full_21175.npz",
                 embedding_dimension = 200,
                 vocabulary = voc,
                 cooc = cooc,
                 load = True)

mat1 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg.txt","train_pos.txt"],
                          label_values=None,
                          input_entries=200000,
                          sentence_dimesion = 200,
                          output_location = "D:\\embedding_matrices\\train_full_21175_1")

mat2 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg.txt","train_pos.txt"],
                          label_values=None,
                          input_entries=200000,
                          aggregation_fun=sentence_embedding.no_embeddings,
                          sentence_dimesion = 100,
                          output_location = "D:\\embedding_matrices\\train_full_21175_0")

Working on  train_neg.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000
Working on  train_neg.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000


### Building training matrix for lemm 5 words

In [12]:
with open("dictionary_lemm_18082.pkl", "rb") as f:
    voc = pickle.load(f)
with open("cooc_lemm_18082.pkl", "rb") as f:
    cooc = pickle.load(f)
    
emb = EmbeddingBase(embedding_name = "emb_lemm_18082.npz",
                 embedding_dimension = 200,
                 vocabulary = voc,
                 cooc = cooc,
                 load = True)

mat1 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_lemmatized.txt","train_pos_lemmatized.txt"],
                          label_values=None,
                          input_entries=200000,
                          sentence_dimesion = 200,
                          output_location = "D:\\embedding_matrices\\train_lemm_18082_1")

mat2 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_lemmatized.txt","train_pos_lemmatized.txt"],
                          label_values=None,
                          input_entries=200000,
                          aggregation_fun=sentence_embedding.no_embeddings,
                          sentence_dimesion = 100,
                          output_location = "D:\\embedding_matrices\\train_lemm_18082_0")

Working on  train_neg_lemmatized.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos_lemmatized.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000
Working on  train_neg_lemmatized.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos_lemmatized.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000


### Building training matrix for lemmatized + stopwords 5 words

In [13]:
with open("dict_lemm_stop_17543.pkl", "rb") as f:
    voc = pickle.load(f)
with open("cooc_lemm_stop_17543.pkl", "rb") as f:
    cooc = pickle.load(f)
    
emb = EmbeddingBase(embedding_name = "emb_lemm_stop_17543.npz",
                 embedding_dimension = 200,
                 vocabulary = voc,
                 cooc = cooc,
                 load = True)

mat1 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_lemmatized.txt","train_pos_lemmatized.txt"],
                          label_values=None,
                          input_entries=200000,
                          sentence_dimesion = 200,
                          output_location = "D:\\embedding_matrices\\train_lemm_stop_17543_1")

mat2 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_lemmatized.txt","train_pos_lemmatized.txt"],
                          label_values=None,
                          input_entries=200000,
                          aggregation_fun=sentence_embedding.no_embeddings,
                          sentence_dimesion = 100,
                          output_location = "D:\\embedding_matrices\\train_lemm_stop_17543_0")

Working on  train_neg_lemmatized.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos_lemmatized.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000
Working on  train_neg_lemmatized.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos_lemmatized.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000


### Building training matrix for lemmatized + replacement5 words

In [ ]:
with open("vocab_lemm_rep_17891_5.pkl", "rb") as f:
    voc = pickle.load(f)
with open("cooc_lemm_rep_17891_5.pkl", "rb") as f:
    cooc = pickle.load(f)
    
emb = EmbeddingBase(embedding_name = "emb_lemm_rep_17891_5.npz",
                 embedding_dimension = 200,
                 vocabulary = voc,
                 cooc = cooc,
                 load = True)

mat1 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_lemm_repl_no_pickle.txt","train_pos_lemm_repl_no_pickle.txt"],
                          label_values=None,
                          input_entries=200000,
                          sentence_dimesion = 200,
                          output_location = "training_matrices\\train_lemm_rep_17891_5_1")

mat2 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_lemm_repl_no_pickle.txt","train_pos_lemm_repl_no_pickle.txt"],
                          label_values=None,
                          input_entries=200000,
                          aggregation_fun=sentence_embedding.no_embeddings,
                          sentence_dimesion = 100,
                          output_location = "training_matrices\\train_lemm_rep_17891_5_0")

### Building training matrix for lemmatized + stopwords 10 words

In [14]:
with open("vocab_lemm_rep_10_10810.pkl", "rb") as f:
    voc = pickle.load(f)
with open("cooc_lemm_rep_10_10810.pkl", "rb") as f:
    cooc = pickle.load(f)
    
emb = EmbeddingBase(embedding_name = "emb_lemm_rep_10_10810.npz",
                 embedding_dimension = 200,
                 vocabulary = voc,
                 cooc = cooc,
                 load = True)

mat1 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_lemm_repl_no_pickle.txt","train_pos_lemm_repl_no_pickle.txt"],
                          label_values=None,
                          input_entries=200000,
                          sentence_dimesion = 200,
                          output_location = "D:\\embedding_matrices\\train_lemm_rep_10_10810_1")

mat2 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_lemm_repl_no_pickle.txt","train_pos_lemm_repl_no_pickle.txt"],
                          label_values=None,
                          input_entries=200000,
                          aggregation_fun=sentence_embedding.no_embeddings,
                          sentence_dimesion = 100,
                          output_location = "D:\\embedding_matrices\\train_lemm_rep_10_10810_0")

Working on  train_neg_lemm_repl_no_pickle.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos_lemm_repl_no_pickle.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000
Working on  train_neg_lemm_repl_no_pickle.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos_lemm_repl_no_pickle.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000


### Building training matrix for negation marking + lemmatized + repl 5 words

In [16]:
with open("dictionary_negation_mark_5.pkl", "rb") as f:
    voc = pickle.load(f)
with open("cooc__negation_mark_5.pkl", "rb") as f:
    cooc = pickle.load(f)
    
emb = EmbeddingBase(embedding_name = "emb_negation_5.npz",
                 embedding_dimension = 200,
                 vocabulary = voc,
                 cooc = cooc,
                 load = True)

mat1 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_negation_mark.txt","train_pos_negation_mark.txt"],
                          label_values=None,
                          input_entries=200000,
                          sentence_dimesion = 200,
                          output_location = "D:\\embedding_matrices\\train_neg_mark_5_1")

mat2 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_negation_mark.txt","train_pos_negation_mark.txt"],
                          label_values=None,
                          input_entries=200000,
                          aggregation_fun=sentence_embedding.no_embeddings,
                          sentence_dimesion = 100,
                          output_location = "D:\\embedding_matrices\\train_neg_mark_5_0")

Working on  train_neg_negation_mark.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos_negation_mark.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000
Working on  train_neg_negation_mark.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos_negation_mark.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000


### Building training matrix for lemmatized + stopwords 10 words

In [17]:
with open("dictionary_negation_mark_10.pkl", "rb") as f:
    voc = pickle.load(f)
with open("cooc__negation_mark_10.pkl", "rb") as f:
    cooc = pickle.load(f)
    
emb = EmbeddingBase(embedding_name = "emb_negation_10.npz",
                 embedding_dimension = 200,
                 vocabulary = voc,
                 cooc = cooc,
                 load = True)

mat1 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_negation_mark.txt","train_pos_negation_mark.txt"],
                          label_values=None,
                          input_entries=200000,
                          sentence_dimesion = 200,
                          output_location = "D:\\embedding_matrices\\train_neg_mark_10_1")

mat2 = pipe.build_training_matrix(label = True,
                          embedding = emb,
                          input_files=["train_neg_negation_mark.txt","train_pos_negation_mark.txt"],
                          label_values=None,
                          input_entries=200000,
                          aggregation_fun=sentence_embedding.no_embeddings,
                          sentence_dimesion = 100,
                          output_location = "D:\\embedding_matrices\\train_neg_mark_10_0")

Working on  train_neg_negation_mark.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos_negation_mark.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000
Working on  train_neg_negation_mark.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Working on  train_pos_negation_mark.txt
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
Number of lines read: 200000
